name = "RealtimeMusicTheory"
uuid = "2f5b4ea4-0f24-4f3b-80d9-07c43c98ce5f"
authors = ["Michael Myers"]
version = "0.2.0"

[compat]
julia = "1.9"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BenchmarkTools", "Test"]
